export type RGB = [number, number, number];

export const PDF_COLORS = {
  primary: [79, 70, 229] as RGB,
  text: [31, 41, 55] as RGB,
  muted: [107, 114, 128] as RGB,
  white: [255, 255, 255] as RGB,
  background: [249, 250, 251] as RGB,
  success: [34, 197, 94] as RGB,
  error: [239, 68, 68] as RGB,
  info: [59, 130, 246] as RGB,
  gray: [156, 163, 175] as RGB,
  divider: [229, 231, 235] as RGB,
};

export const STATUS_COLORS: Record<string, RGB> = {
  PAID: PDF_COLORS.success,
  OVERDUE: PDF_COLORS.error,
  SENT: PDF_COLORS.info,
  VIEWED: PDF_COLORS.info,
  DRAFT: PDF_COLORS.gray,
};

export const LAYOUT = {
  MARGIN: 20,
  SECTION_LABEL_SIZE: 10,

  HEADER_TITLE_SIZE: 28,
  HEADER_TITLE_Y: 30,
  HEADER_ID_SIZE: 12,
  HEADER_ID_Y: 38,
  STATUS_BADGE_WIDTH: 30,
  STATUS_BADGE_HEIGHT: 10,
  STATUS_BADGE_Y: 22,
  STATUS_BADGE_RADIUS: 2,
  STATUS_FONT_SIZE: 8,
  STATUS_TEXT_OFFSET_Y: 7,

  INFO_START_Y: 55,
  INFO_LINE_HEIGHT: 5,
  INFO_LABEL_OFFSET: 7,
  INFO_FONT_SIZE: 11,

  DATES_Y: 100,
  DATES_HEIGHT: 25,
  DATES_RADIUS: 3,
  DATES_LABEL_SIZE: 9,
  DATES_LABEL_OFFSET: 3,
  DATES_VALUE_OFFSET: 12,
  DATES_VALUE_SIZE: 10,
  DATES_COL_1: 30,
  DATES_COL_2: 90,
  DATES_COL_3: 150,

  TABLE_START_Y: 135,
  TABLE_HEAD_SIZE: 9,
  TABLE_BODY_SIZE: 10,
  TABLE_COL_ITEM: 80,
  TABLE_COL_QTY: 25,
  TABLE_COL_PRICE: 40,
  TABLE_COL_AMOUNT: 40,
  TABLE_END_GAP: 15,

  TOTALS_WIDTH: 70,
  TOTALS_OFFSET_X: 90,
  TOTALS_LINE_HEIGHT: 8,
  TOTALS_FONT_SIZE: 10,
  TOTALS_TOTAL_SIZE: 12,
  TOTALS_SEPARATOR_GAP: 10,

  NOTES_GAP: 25,
  NOTES_LABEL_SIZE: 9,
  NOTES_LABEL_OFFSET: 6,
  NOTES_BODY_SIZE: 10,

  FOOTER_OFFSET_Y: 20,
  FOOTER_FONT_SIZE: 8,
} as const;
