export const SHORTCUTS = {
  COMMAND_PALETTE: {
    key: "k",
    ctrl: true,
    keys: ["Ctrl", "K"],
    description: "Open command palette",
    group: "General",
  },
  SHORTCUTS_DIALOG: {
    key: "?",
    keys: ["?"],
    description: "Show keyboard shortcuts",
    group: "General",
  },
  NEW_INVOICE: {
    key: "n",
    ctrl: true,
    keys: ["Ctrl", "N"],
    description: "Create new invoice",
    group: "Actions",
  },
  GO_DASHBOARD: {
    key: "d",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "D"],
    description: "Go to dashboard",
    group: "Navigation",
  },
  GO_INVOICES: {
    key: "g",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "G"],
    description: "Go to invoices",
    group: "Navigation",
  },
  GO_CLIENTS: {
    key: "c",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "C"],
    description: "Go to clients",
    group: "Navigation",
  },
  GO_TEMPLATES: {
    key: "t",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "T"],
    description: "Go to templates",
    group: "Navigation",
  },
  GO_RECURRING: {
    key: "r",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "R"],
    description: "Go to recurring",
    group: "Navigation",
  },
  GO_SETTINGS: {
    key: "s",
    ctrl: true,
    shift: true,
    keys: ["Ctrl", "Shift", "S"],
    description: "Go to settings",
    group: "Navigation",
  },
  CLOSE: { key: "Escape", keys: ["Esc"], description: "Close dialog", group: "General" },
} as const;

export const STORAGE_KEYS = {
  RECENT_ITEMS: "getpaid-recent-items",
  INVOICE_DRAFT: "invoice-draft-new",
  ONBOARDING_DISMISSED: "getpaid-onboarding-dismissed",
  THEME_MODE: "theme-mode",
  SIDEBAR_COLLAPSED: "getpaid-sidebar-collapsed",
} as const;
